apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: production
  name: worpressfinal-pv
  labels:
    app: wordpress
spec:
  capacity:
    storage: 4Gi
  storageClassName: default
  azureDisk:
    cachingMode: None
    diskName: wordpressfinalnew
    diskURI: /subscriptions/c0812314-9889-42e6-8d45-4b13cfa76c0a/resourceGroups/K8s/providers/Microsoft.Compute/disks/wordpressfinalnew
    kind: Managed
    fsType: ext4
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  claimRef:
    name: worpressfinal-pvc
    namespace: production
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: production
  name: worpressfinal-pvc
  annotations:
    volume.beta.kubernetes.io/storage-class: default
  labels:
    app: wordpress
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: default
