# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name: myk8s
  demands:
  - hostname

steps:
- task: Docker@2
  inputs:
    containerRegistry: 'acr'
    repository: 'test'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'

