apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: worpressfinal-pvc
  namespace: production
  labels:
    app: wordpress
spec:
  accessModes:
  - {{ .Values.persistence.accessMode }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
  storageClassName: {{ .Values.persistence.storageClass }}

